### ISSUE TITLE
[版本计划] v1.1.2将于4月初发布 

### ISSUE THREAD

**Issue by xl1605368195** [jvm-rasp/jrasp-agent#15]
v1.1.2 版本新特性
- web 管理端使用 golang 重写，占用资源更少，更加安全，整个管理端仅需要一台机器即可
- 取消 kafka、zookeeper、nacos 等Java 主件，保证功能的同时，更加安全
- 数据库使用默认使用sqlite

**Comment by jvm-rasp** [comment]
OK
