### ISSUE TITLE
文件重命名Hook点传参Bug

### ISSUE THREAD

**Issue by yggo** [jvm-rasp/jrasp-agent#17]
类路径：`com.jrasp.agent.module.file.hook.FileHook`

Hook点：`renameTo(Ljava/io/File;)Z`

修复后的代码：`algorithmManager.doCheck(FILE_UPLOAD, requestInfoThreadLocal.get(), advice.getParameterArray()[0]);`

![image](https://user-images.githubusercontent.com/27994074/234778825-6c3bbada-7a1b-4fb6-9f0e-8d30acba3b69.png)

**Comment by xl1605368195** [comment]
已经修复
