### ISSUE TITLE
[建议] 增加一个自定义的响应头，如：X-Protected-By：JRASP

### ISSUE THREAD

**Issue by yupd** [jvm-rasp/jrasp-agent#34]

**Comment by xl1605368195** [comment]
已经解决：https://github.com/jvm-rasp/jrasp-agent/commit/b4a11e1d556804d69a2ae4d9cba87bd996072976
<img width="1091" alt="image" src="https://github.com/jvm-rasp/jrasp-agent/assets/26989019/7d7b17e2-29f5-434e-bc67-0813f76d3507">
