### ISSUE TITLE
官方文档filebeat安装部分，ubuntu操作系统不兼容问题

### ISSUE THREAD

**Issue by meifukun** [jvm-rasp/jrasp-agent#40]
在Ubuntu中安装filebeat后无法正常启动，但在centos中可以正常运行

**Comment by meifukun** [comment]
Ubuntu中使用systemctl自启动后的报错截图：
![image](https://github.com/jvm-rasp/jrasp-agent/assets/146064974/47e40ccc-7ea7-4bc8-a587-450dc6cf6754)
手动启动的报错截图：
![image](https://github.com/jvm-rasp/jrasp-agent/assets/146064974/e500af44-b28a-458f-925c-e8a5ab5d5a98)
centos操作系统中的正常启动截图：
![image](https://github.com/jvm-rasp/jrasp-agent/assets/146064974/03af31ad-764f-44a2-9f5b-daecf21a018e)

**Comment by xl1605368195** [comment]
确认是filebeat 问题：https://github.com/elastic/beats/pull/28117#issuecomment-1001973457
新版本filebeat 使用 7.17.4 ，验证没有问题。
下载链接：https://jrasp-daemon-1254321150.cos.ap-shanghai.myqcloud.com/v1.1.3-20240102/filebeat-1.1.3-linux-x86_64.tar.gz
