### ISSUE TITLE
service.sh 进程探活逻辑优化

### ISSUE THREAD

**Issue by orange-777** [jvm-rasp/jrasp-agent#41]
$ ps aux | grep jrasp-daemon | grep -v grep
root      69327  0.0  0.0 108096   556 pts/3    S+   18:42   0:00 tail -f logs/jrasp-daemon.log

命令行包含jrasp-daemon会导致jrasp-daemon无法启动

**Comment by xl1605368195** [comment]
![image](https://github.com/jvm-rasp/jrasp-agent/assets/26989019/8943922e-f041-49b5-a269-2d530f272f6f)

service.sh 里面得探活机制有点问题，会把这个进程当成成rasp进程，因为命令行包含了jrasp-daemon
![image](https://github.com/jvm-rasp/jrasp-agent/assets/26989019/1e05144b-f21b-43d5-ba48-3cad869e0794)

**Comment by xl1605368195** [comment]
已经解决。
https://github.com/jvm-rasp/jrasp-agent/commit/59c443e0100feea8f58346cc14cf1665cdb369f7
