### ISSUE TITLE
[bug] request.getRequestURL() 存在绕过的问题

### ISSUE THREAD

**Issue by yupd** [jvm-rasp/jrasp-agent#46]
例如：对 url `/demo/test.do` 设置黑名单，可以通过 `/demo/;xx/test.do` 绕过。

**Comment by jvm-rasp** [comment]
当前计划增加url特殊字符串检测功能，禁止在url中出现`;`等字符

**Comment by yupd** [comment]
> 当前计划增加url特殊字符串检测功能，禁止在url中出现`;`等字符

使用 request.getServletPath() 是最终的请求的地址，用这个方法取代 request.getRequestURL() 是不是好点？

**Comment by jvm-rasp** [comment]
好的，我看下。为了兼容性，增加一个真实url字段。 
检测url中特殊字符串功能已经增加

**Comment by jvm-rasp** [comment]
https://github.com/jvm-rasp/jrasp-agent/commit/243e5a753a269d0722b6ebb0d291a2c7323db7bf
