### ISSUE TITLE
上传的压缩包里面包含jsp或exe文件解压会被拦截有办法解决吗？

### ISSUE THREAD

**Issue by yupd** [jvm-rasp/jrasp-agent#51]
场景是系统升级一般会上传一个zip包，里面包含各种各样的文件。

**Comment by jvm-rasp** [comment]
拦截的日志发一下

**Comment by jvm-rasp** [comment]
默认测了不会拦截，只有告警

**Comment by yupd** [comment]
> 拦截的日志发一下

[jrasp-attack-0.log](https://github.com/jvm-rasp/jrasp-agent/files/13224885/jrasp-attack-0.log)

> 开启 "file_upload_action": 1

**Comment by yupd** [comment]
我的做法是添加一个允许写入的url白名单，里面把类似上传压缩包的配置白名单，但是感觉不太好，得把业务系统的url都得给穷举出来。

**Comment by xl1605368195** [comment]
可以增加url白名单，先解决误报。先不要开阻断，确认没有误报后在开启
