### ISSUE TITLE
1.1.3 版本中 jrasp-daemon service 守护进程一直无法启动

### ISSUE THREAD

**Issue by Drun1baby** [jvm-rasp/jrasp-agent#58]
根据文档来的 https://www.jrasp.com/guide/install/v1.1.3/install-all.html

报错如图

root@VM-12-14-debian:~# systemctl status jrasp-daemon.service
● jrasp-daemon.service - jrasp-daemon service
     Loaded: loaded (/lib/systemd/system/jrasp-daemon.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2024-02-28 11:34:52 CST; 1min 52s ago
   Main PID: 3428779 (code=exited, status=2)
        CPU: 33ms

Feb 28 11:34:52 VM-12-14-debian systemd[1]: jrasp-daemon.service: Scheduled restart job, restart counter is at 5.
Feb 28 11:34:52 VM-12-14-debian systemd[1]: Stopped jrasp-daemon service.
Feb 28 11:34:52 VM-12-14-debian systemd[1]: jrasp-daemon.service: Start request repeated too quickly.
Feb 28 11:34:52 VM-12-14-debian systemd[1]: jrasp-daemon.service: Failed with result 'exit-code'.
Feb 28 11:34:52 VM-12-14-debian systemd[1]: Failed to start jrasp-daemon service.

![image](https://github.com/jvm-rasp/jrasp-agent/assets/75228348/6890fadf-93b9-4096-9a50-6456ec40aa10)

**Comment by xl1605368195** [comment]
只启动jrasp-daemon，不使用system启动，看下是否能够正常启动。 @Drun1baby

**Comment by Drun1baby** [comment]
意思是，只启动 rasp 项目，但是不配置 **jrasp-daemon需要配置守护进程！！！** 这个东西吗？

**Comment by xl1605368195** [comment]
> 意思是，只启动 rasp 项目，但是不配置 **jrasp-daemon需要配置守护进程！！！** 这个东西吗？

![图片](https://github.com/jvm-rasp/jrasp-agent/assets/26989019/a0897151-3181-4e73-94f3-cf12f11f4609)

**Comment by Drun1baby** [comment]
> > 意思是，只启动 rasp 项目，但是不配置 **jrasp-daemon需要配置守护进程！！！** 这个东西吗？
> 
> ![图片](https://private-user-images.githubusercontent.com/26989019/308463540-a0897151-3181-4e73-94f3-cf12f11f4609.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDY5MjQsIm5iZiI6MTcwOTEwNjYyNCwicGF0aCI6Ii8yNjk4OTAxOS8zMDg0NjM1NDAtYTA4OTcxNTEtMzE4MS00ZTczLTk0ZjMtY2YxMmYxMWY0NjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA3NTAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMjZkNTAxNTMxYWE1NmQ2NjhhODY4ZTE3MjliMGE2ZmQzODFlZTE3YTUxNjI4NjZkNTc4N2JhZDEzMzhkNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cq2WtWX9vbHkiJZHLBQCnCk-XI4vLH1-9e0oEjdGRH4)

这样子可以启动 RASP

**Comment by xl1605368195** [comment]
看上去是systemd的问题，操作系统版本，发一下，我找台机器看下。

**Comment by Drun1baby** [comment]
Linux VM-12-14-debian 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux

**Comment by xl1605368195** [comment]
没有发现什么问题。自行排查下或者安装supervisor 工具
