### ISSUE TITLE
文档一个小错误

### ISSUE THREAD

**Issue by vvmdx** [jvm-rasp/jrasp-agent#62]
[安装教程](https://www.jrasp.com/guide/quick-start.html#_02-jrasp-agent%E5%AE%89%E8%A3%85) 的”下载 agent“是v1.1.5，下一步解压的命令是v1.1.3
![image](https://github.com/jvm-rasp/jrasp-agent/assets/75788310/d0d90c47-6762-4af8-bd56-f0e42aff8db2)

**Comment by hycsxs** [comment]
> [安装教程](https://www.jrasp.com/guide/quick-start.html#_02-jrasp-agent%E5%AE%89%E8%A3%85) 的”下载 agent“是v1.1.5，下一步解压的命令是v1.1.3 ![image](https://private-user-images.githubusercontent.com/75788310/344100516-d0d90c47-6762-4af8-bd56-f0e42aff8db2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NTgxNDksIm5iZiI6MTcyMDY1Nzg0OSwicGF0aCI6Ii83NTc4ODMxMC8zNDQxMDA1MTYtZDBkOTBjNDctNjc2Mi00YWY4LWJkNTYtZjBlNDJhZmY4ZGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDAwMzA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MzAzM2JiYzM0YzA2ZTJhMTMxMWMzMjcxN2FmYmZjZWNmMDdjMTkzZTJjNDk1OTBhZjIyNDUyOWExOGU5MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dJkp3bi1MFurQfoEtb0mDXvgfDNqjtV7IasSJzGXlyU)

安装教程文档已修复
